// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AppBar : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AppBar GetRootAsAppBar(ByteBuffer _bb) { return GetRootAsAppBar(_bb, new AppBar()); }
  public static AppBar GetRootAsAppBar(ByteBuffer _bb, AppBar obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AppBar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Nebula.Ast.Widget? Title { get { int o = __p.__offset(4); return o != 0 ? (Nebula.Ast.Widget?)(new Nebula.Ast.Widget()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Nebula.Ast.AppBar> CreateAppBar(FlatBufferBuilder builder,
      Offset<Nebula.Ast.Widget> titleOffset = default(Offset<Nebula.Ast.Widget>)) {
    builder.StartTable(1);
    AppBar.AddTitle(builder, titleOffset);
    return AppBar.EndAppBar(builder);
  }

  public static void StartAppBar(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTitle(FlatBufferBuilder builder, Offset<Nebula.Ast.Widget> titleOffset) { builder.AddOffset(0, titleOffset.Value, 0); }
  public static Offset<Nebula.Ast.AppBar> EndAppBar(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Nebula.Ast.AppBar>(o);
  }
}


static public class AppBarVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Title*/, Nebula.Ast.WidgetVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
