// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Button : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Button GetRootAsButton(ByteBuffer _bb) { return GetRootAsButton(_bb, new Button()); }
  public static Button GetRootAsButton(ByteBuffer _bb, Button obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Button __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Nebula.Ast.Widget? Text { get { int o = __p.__offset(4); return o != 0 ? (Nebula.Ast.Widget?)(new Nebula.Ast.Widget()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Nebula.Ast.Handler? Handler { get { int o = __p.__offset(6); return o != 0 ? (Nebula.Ast.Handler?)(new Nebula.Ast.Handler()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Nebula.Ast.Button> CreateButton(FlatBufferBuilder builder,
      Offset<Nebula.Ast.Widget> textOffset = default(Offset<Nebula.Ast.Widget>),
      Offset<Nebula.Ast.Handler> handlerOffset = default(Offset<Nebula.Ast.Handler>)) {
    builder.StartTable(2);
    Button.AddHandler(builder, handlerOffset);
    Button.AddText(builder, textOffset);
    return Button.EndButton(builder);
  }

  public static void StartButton(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddText(FlatBufferBuilder builder, Offset<Nebula.Ast.Widget> textOffset) { builder.AddOffset(0, textOffset.Value, 0); }
  public static void AddHandler(FlatBufferBuilder builder, Offset<Nebula.Ast.Handler> handlerOffset) { builder.AddOffset(1, handlerOffset.Value, 0); }
  public static Offset<Nebula.Ast.Button> EndButton(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Nebula.Ast.Button>(o);
  }
}


static public class ButtonVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Text*/, Nebula.Ast.WidgetVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*Handler*/, Nebula.Ast.HandlerVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
