// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ElevatedButton : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ElevatedButton GetRootAsElevatedButton(ByteBuffer _bb) { return GetRootAsElevatedButton(_bb, new ElevatedButton()); }
  public static ElevatedButton GetRootAsElevatedButton(ByteBuffer _bb, ElevatedButton obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ElevatedButton __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Nebula.Ast.Widget? Child { get { int o = __p.__offset(4); return o != 0 ? (Nebula.Ast.Widget?)(new Nebula.Ast.Widget()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Nebula.Ast.Handler? OnPressedHandler { get { int o = __p.__offset(6); return o != 0 ? (Nebula.Ast.Handler?)(new Nebula.Ast.Handler()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Nebula.Ast.ElevatedButton> CreateElevatedButton(FlatBufferBuilder builder,
      Offset<Nebula.Ast.Widget> childOffset = default(Offset<Nebula.Ast.Widget>),
      Offset<Nebula.Ast.Handler> on_pressed_handlerOffset = default(Offset<Nebula.Ast.Handler>)) {
    builder.StartTable(2);
    ElevatedButton.AddOnPressedHandler(builder, on_pressed_handlerOffset);
    ElevatedButton.AddChild(builder, childOffset);
    return ElevatedButton.EndElevatedButton(builder);
  }

  public static void StartElevatedButton(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddChild(FlatBufferBuilder builder, Offset<Nebula.Ast.Widget> childOffset) { builder.AddOffset(0, childOffset.Value, 0); }
  public static void AddOnPressedHandler(FlatBufferBuilder builder, Offset<Nebula.Ast.Handler> onPressedHandlerOffset) { builder.AddOffset(1, onPressedHandlerOffset.Value, 0); }
  public static Offset<Nebula.Ast.ElevatedButton> EndElevatedButton(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Nebula.Ast.ElevatedButton>(o);
  }
}


static public class ElevatedButtonVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Child*/, Nebula.Ast.WidgetVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*OnPressedHandler*/, Nebula.Ast.HandlerVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
