// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GoHandler : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GoHandler GetRootAsGoHandler(ByteBuffer _bb) { return GetRootAsGoHandler(_bb, new GoHandler()); }
  public static GoHandler GetRootAsGoHandler(ByteBuffer _bb, GoHandler obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GoHandler __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Route { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRouteBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRouteBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRouteArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Nebula.Ast.GoHandler> CreateGoHandler(FlatBufferBuilder builder,
      StringOffset routeOffset = default(StringOffset)) {
    builder.StartTable(1);
    GoHandler.AddRoute(builder, routeOffset);
    return GoHandler.EndGoHandler(builder);
  }

  public static void StartGoHandler(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRoute(FlatBufferBuilder builder, StringOffset routeOffset) { builder.AddOffset(0, routeOffset.Value, 0); }
  public static Offset<Nebula.Ast.GoHandler> EndGoHandler(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Nebula.Ast.GoHandler>(o);
  }
}


static public class GoHandlerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Route*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
