// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

public enum HandlerType : sbyte
{
  Go = 0,
  SetState = 1,
  Composite = 2,
  Print = 3,
  SetStateWithValue = 4,
};


}
