// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

public enum HandlerData : byte
{
  NONE = 0,
  GoHandler = 1,
  SetStateHandler = 2,
  PrintHandler = 3,
  SetStateHandlerWithValue = 4,
  CompositeHandler = 5,
};



static public class HandlerDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((HandlerData)typeId)
    {
      case HandlerData.GoHandler:
        result = Nebula.Ast.GoHandlerVerify.Verify(verifier, tablePos);
        break;
      case HandlerData.SetStateHandler:
        result = Nebula.Ast.SetStateHandlerVerify.Verify(verifier, tablePos);
        break;
      case HandlerData.PrintHandler:
        result = Nebula.Ast.PrintHandlerVerify.Verify(verifier, tablePos);
        break;
      case HandlerData.SetStateHandlerWithValue:
        result = Nebula.Ast.SetStateHandlerWithValueVerify.Verify(verifier, tablePos);
        break;
      case HandlerData.CompositeHandler:
        result = Nebula.Ast.CompositeHandlerVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
