// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Row : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Row GetRootAsRow(ByteBuffer _bb) { return GetRootAsRow(_bb, new Row()); }
  public static Row GetRootAsRow(ByteBuffer _bb, Row obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Row __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Nebula.Ast.Widget? ChildrenExprs(int j) { int o = __p.__offset(4); return o != 0 ? (Nebula.Ast.Widget?)(new Nebula.Ast.Widget()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChildrenExprsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Nebula.Ast.Row> CreateRow(FlatBufferBuilder builder,
      VectorOffset children_exprsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Row.AddChildrenExprs(builder, children_exprsOffset);
    return Row.EndRow(builder);
  }

  public static void StartRow(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddChildrenExprs(FlatBufferBuilder builder, VectorOffset childrenExprsOffset) { builder.AddOffset(0, childrenExprsOffset.Value, 0); }
  public static VectorOffset CreateChildrenExprsVector(FlatBufferBuilder builder, Offset<Nebula.Ast.Widget>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChildrenExprsVectorBlock(FlatBufferBuilder builder, Offset<Nebula.Ast.Widget>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenExprsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Nebula.Ast.Widget>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenExprsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Nebula.Ast.Widget>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChildrenExprsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Nebula.Ast.Row> EndRow(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Nebula.Ast.Row>(o);
  }
}


static public class RowVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*ChildrenExprs*/, Nebula.Ast.WidgetVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
