// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

public enum WidgetType : sbyte
{
  Scaffold = 0,
  AppBar = 1,
  Body = 2,
  Text = 3,
  Button = 4,
  Row = 5,
  Column = 6,
  ElevatedButton = 7,
};


}
