// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Nebula.Ast
{

public enum WidgetData : byte
{
  NONE = 0,
  Scaffold = 1,
  AppBar = 2,
  Body = 3,
  Text = 4,
  Button = 5,
  Row = 6,
  Column = 7,
  ElevatedButton = 8,
};



static public class WidgetDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((WidgetData)typeId)
    {
      case WidgetData.Scaffold:
        result = Nebula.Ast.ScaffoldVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.AppBar:
        result = Nebula.Ast.AppBarVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.Body:
        result = Nebula.Ast.BodyVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.Text:
        result = Nebula.Ast.TextVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.Button:
        result = Nebula.Ast.ButtonVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.Row:
        result = Nebula.Ast.RowVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.Column:
        result = Nebula.Ast.ColumnVerify.Verify(verifier, tablePos);
        break;
      case WidgetData.ElevatedButton:
        result = Nebula.Ast.ElevatedButtonVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
